# Generated by Django 3.2.6 on 2021-09-23 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(auto_now=True)),
                ('sistema', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(auto_now=True)),
                ('edificio', models.CharField(max_length=20)),
                ('elemento', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('imagen', models.ImageField(null=True, upload_to='elementos')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.sistemamodel')),
            ],
        ),
    ]
