# Generated by Django 3.2.6 on 2021-09-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementomodel',
            name='estado',
            field=models.BigIntegerField(choices=[{0, 'Fuera de servicio'}, {1, 'En servicio'}], default=1),
            preserve_default=False,
        ),
    ]
