# Generated by Django 3.2.6 on 2021-09-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_elementomodel_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementomodel',
            name='ubicación',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elementomodel',
            name='elemento',
            field=models.CharField(max_length=50),
        ),
    ]
