# Generated by Django 3.2.6 on 2021-09-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_auto_20210927_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementomodel',
            name='ubicacion',
            field=models.CharField(max_length=10),
        ),
    ]
