# Generated by Django 3.2.6 on 2021-09-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_alter_elementomodel_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementomodel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='elementos'),
        ),
        migrations.CreateModel(
            name='PreventivoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(auto_now=True, null=True)),
                ('tipo', models.IntegerField(choices=[{0, 'Preventivo'}, {1, 'Correctivo'}])),
                ('descripcion', models.CharField(max_length=200)),
                ('observacion', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='preventivo')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.elementomodel')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectivoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(auto_now=True, null=True)),
                ('tipo', models.IntegerField(choices=[{0, 'Preventivo'}, {1, 'Correctivo'}])),
                ('descripcion', models.CharField(max_length=200)),
                ('observacion', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='correctivo')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.elementomodel')),
            ],
        ),
    ]
