# Generated by Django 3.2.6 on 2021-09-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_auto_20210929_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctivomodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='correctivo'),
        ),
    ]
