# Generated by Django 3.2.6 on 2021-10-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0009_auto_20211002_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementomodel',
            name='edificio',
            field=models.CharField(max_length=20),
        ),
    ]
