# Generated by Django 3.2.6 on 2021-10-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0006_alter_presupuesto_rubro_frecuencia'),
        ('mantenimiento', '0010_alter_elementomodel_edificio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementomodel',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.edificio_model'),
        ),
    ]
