# Generated by Django 3.2.6 on 2021-10-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0011_alter_elementomodel_edificio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otmodel',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='otmodel',
            name='tipo',
            field=models.BigIntegerField(choices=[{0, 'Preventivo'}, {1, 'Correctivo'}], default=1),
            preserve_default=False,
        ),
    ]
