# Generated by Django 3.2.6 on 2021-10-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0012_auto_20211002_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otmodel',
            name='fecha_fin',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='otmodel',
            name='fecha_inicio',
            field=models.DateField(blank=True),
        ),
    ]
