# Generated by Django 3.2.6 on 2021-09-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(auto_now=True)),
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=15)),
                ('contacto', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto_Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('creado', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.BooleanField(choices=[[0, 'Propietario'], [1, 'Ocupante']])),
                ('apartamento', models.CharField(max_length=5)),
                ('correo', models.EmailField(max_length=254)),
                ('contacto_1', models.CharField(max_length=14)),
                ('contacto_2', models.CharField(blank=True, max_length=14)),
                ('estado', models.BooleanField(choices=[[0, 'Disponible'], [1, 'Ocupado']])),
                ('creado', models.DateTimeField(auto_now=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edificios.edificio_model')),
            ],
        ),
        migrations.CreateModel(
            name='Visitante_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('vehiculo', models.BooleanField(blank=True, choices=[{0, 'Carro'}, {1, 'Moto'}])),
                ('placa', models.CharField(blank=True, max_length=14)),
                ('creado', models.DateTimeField(auto_now=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edificios.propietario_model')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto_Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('frecuencia', models.BooleanField(choices=[[1, 'Mesual'], [2, 'Semestral'], [3, 'Trimestral'], [4, 'Cuatrimestral'], [5, 'Semestral'], [6, 'Anual']])),
                ('mes', models.BooleanField(choices=[[1, 'Enero'], [2, 'Febrero'], [3, 'Marzo'], [4, 'Abril'], [5, 'Mayo'], [6, 'Junio'], [7, 'Julio'], [8, 'Agosto'], [9, 'Septiembre'], [10, 'Octubre'], [11, 'Noviembre'], [12, 'Diciembre']])),
                ('valor', models.CharField(max_length=20)),
                ('creado', models.DateTimeField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edificios.presupuesto_tipo')),
            ],
        ),
    ]
