# Generated by Django 3.2.6 on 2021-09-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Presupuesto_Tipo',
            new_name='Presupuesto_Cuenta',
        ),
    ]
