# Generated by Django 3.2.6 on 2021-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0002_rename_presupuesto_tipo_presupuesto_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto_rubro',
            name='frecuencia',
            field=models.IntegerField(choices=[[1, 'Mesual'], [2, 'Semestral'], [3, 'Trimestral'], [4, 'Cuatrimestral'], [5, 'Semestral'], [6, 'Anual']]),
        ),
        migrations.AlterField(
            model_name='presupuesto_rubro',
            name='mes',
            field=models.IntegerField(choices=[[1, 'Enero'], [2, 'Febrero'], [3, 'Marzo'], [4, 'Abril'], [5, 'Mayo'], [6, 'Junio'], [7, 'Julio'], [8, 'Agosto'], [9, 'Septiembre'], [10, 'Octubre'], [11, 'Noviembre'], [12, 'Diciembre']]),
        ),
        migrations.AlterField(
            model_name='presupuesto_rubro',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
        migrations.AlterField(
            model_name='visitante_model',
            name='vehiculo',
            field=models.BooleanField(blank=True, choices=[[0, 'Carro'], [1, 'Moto']]),
        ),
    ]
