# Generated by Django 3.2.6 on 2021-09-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0003_auto_20210923_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto_rubro',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
    ]
