# Generated by Django 3.2.6 on 2021-09-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0004_alter_presupuesto_rubro_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante_model',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.propietario_model'),
        ),
    ]
