# Generated by Django 3.2.6 on 2021-09-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0005_alter_visitante_model_apartamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto_rubro',
            name='frecuencia',
            field=models.IntegerField(choices=[[1, 'Mesual'], [2, 'Semestral'], [3, 'Trimestral'], [4, 'Cuatrimestral'], [5, 'Semestral'], [6, 'Anual']], default=0),
        ),
    ]
